### ISSUE TITLE
N2V Fiji crashes

### ISSUE THREAD

**Issue by Eddymorphling** [juglab/n2v#140]
The N2V Fiji plugin recently stopped working after the latest release of Fiji updates. It was working well in the past on my NVIDIA GPU and TF in Fiji. I also created a post about this on the ImageJ forum ([link](https://forum.image.sc/t/noise2void-error-after-fiji-update/83871)). The error message I get is below. Any clue what could be causing the issue?

```
java.lang.IllegalStateException: Generated message class "org.tensorflow.framework.TensorInfo" missing method "hasName".
	at com.google.protobuf.GeneratedMessageV3.getMethodOrDie(GeneratedMessageV3.java:1998)
	at com.google.protobuf.GeneratedMessageV3.access$1000(GeneratedMessageV3.java:79)
	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularFieldAccessor$ReflectionInvoker.<init>(GeneratedMessageV3.java:2351)
	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularFieldAccessor.<init>(GeneratedMessageV3.java:2418)
	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable$SingularStringFieldAccessor.<init>(GeneratedMessageV3.java:3071)
	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable.ensureFieldAccessorsInitialized(GeneratedMessageV3.java:2137)
	at org.tensorflow.framework.TensorInfo.internalGetFieldAccessorTable(TensorInfo.java:130)
	at com.google.protobuf.GeneratedMessageV3.getDescriptorForType(GeneratedMessageV3.java:139)
	at com.google.protobuf.TextFormat$Printer.print(TextFormat.java:363)
	at com.google.protobuf.TextFormat$Printer.print(TextFormat.java:353)
	at com.google.protobuf.TextFormat$Printer.printToString(TextFormat.java:615)
	at com.google.protobuf.AbstractMessage.toString(AbstractMessage.java:110)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at java.util.AbstractMap.toString(AbstractMap.java:559)
	at com.google.protobuf.MapField$MutabilityAwareMap.toString(MapField.java:372)
	at java.util.Collections$UnmodifiableMap.toString(Collections.java:1495)
	at net.imagej.modelzoo.consumer.model.tensorflow.TensorFlowModel.loadSignature(TensorFlowModel.java:164)
	at net.imagej.modelzoo.consumer.model.tensorflow.TensorFlowModel.loadModel(TensorFlowModel.java:154)
	at net.imagej.modelzoo.DefaultModelZooArchive.createModelInstance(DefaultModelZooArchive.java:119)
	at net.imagej.modelzoo.consumer.AbstractModelZooPrediction.loadModel(AbstractModelZooPrediction.java:156)
	at net.imagej.modelzoo.consumer.AbstractModelZooPrediction.run(AbstractModelZooPrediction.java:99)
	at net.imagej.modelzoo.consumer.command.AbstractSingleImagePredictionCommand.run(AbstractSingleImagePredictionCommand.java:101)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.NoSuchMethodException: org.tensorflow.framework.TensorInfo.hasName()
	at java.lang.Class.getMethod(Class.java:1786)
	at com.google.protobuf.GeneratedMessageV3.getMethodOrDie(GeneratedMessageV3.java:1995)
	... 31 more
[INFO] ModelZoo prediction exit (took 37 milliseconds)
[INFO] Using native TensorFlow version: TF 1.15.0 GPU (CUDA 10.0, CuDNN >= 7.4.1)
[INFO] Loading TensorFlow model unnamed_n2v_lowest_loss_1689638947759 from source file file:/C:/Users/praveen/AppData/Local/Temp/tf_saved_model_bundle4781063617951810542.zip
```

Thanks a bunch!

**Comment by Eddymorphling** [comment]
Got it. Thanks!
